fix(ci): Update MSRV for clippy to 1.64
Required for clap:

   error: failed to select a version for the requirement `clap = "=4.1.4"`
   candidate versions found which didn't match: 3.2.23, 3.2.22, 3.2.21, ...